#!/usr/bin/env python3
"""
-------------------------------------------------------------------------------
 UART Log Parser for MiniSoC-RV32I
-------------------------------------------------------------------------------
 This script analyzes the log generated by the Verilog testbench (mini_rv32i_top.log) 
 to extract the UART characters decoded by the hardware monitor. 
 It reconstructs the display as it would appear in a real terminal 
 (PuTTY, TeraTerm) and generates a clean plain text file.
-------------------------------------------------------------------------------
"""

import sys
import os

def main():
    # Defining the default path if no argument is provided
    default_log_path = "mini_rv32i_top.log"
    
    log_file = sys.argv[1] if len(sys.argv) > 1 else default_log_path

    if not os.path.exists(log_file):
        print(f"[ERROR] The log file '{log_file}' could not be found.")
        print("Usage: python3 parse_uart.py <path_to_mini_rv32i_top.log>")
        sys.exit(1)

    print("\n" + "="*60)
    print(" VIRTUAL UART TERMINAL (MiniSoC-RV32I)")
    print("="*60)

    uart_text = ""
    
    # Log reading with error handling for encoding (to ignore potentially corrupted characters)
    with open(log_file, "r", encoding="utf-8", errors="ignore") as f:
        for line in f:
            # We are looking for the specific tag inserted by the 'UART Monitor' block of the testbench
            if "[UART TERMINAL]" in line:
                # The monitor's initialization message is ignored.
                if "Listening..." in line:
                    continue
                
                # The testbench performs: $fwrite(log_file, "\n[UART TERMINAL] %c", rx_byte);
                # The line is truncated at the tag. The character is immediately after the space.
                parts = line.split("[UART TERMINAL] ")
                if len(parts) >= 2:
                    # We extract exactly the first character following the space.
                    # This preserves the true '\r' and '\n' characters sent by C.
                    char = parts[1][0] 
                    uart_text += char
                    
                    # Real-time printing in the Python console (flush for instant display)
                    print(char, end='', flush=True)

    print("\n" + "="*60)
    
    # Creating the path for the output file
    output_dir = os.path.dirname(log_file)
    if not output_dir:
        output_dir = "."
    out_file = os.path.join(output_dir, "uart_clean_output.txt")
    
    # Sauvegarde du texte brut
    with open(out_file, "w", encoding="utf-8") as f:
        f.write(uart_text)
        
    print(f"\n[INFO] The UART extraction was saved in: {out_file}\n")

if __name__ == "__main__":
    main()