# ==============================================================================
# sim_minisoc/include.sim_minisoc.mk : Complete System Simulation
# ==============================================================================
# This Makefile builds and runs the complete MiniSoC with C-generated firmware
# ==============================================================================

# ----------------------------------------------------------------------------
# Configuration
# ----------------------------------------------------------------------------
SIM_MINISOC_DIR       := $(TOP_DIR)/sim_minisoc
SIM_MINISOC_BUILD_DIR ?= $(BUILD_DIR)/sim_minisoc
export SIM_MINISOC_DIR SIM_MINISOC_BUILD_DIR

# ----------------------------------------------------------------------------
# Tracer Configuration
# ----------------------------------------------------------------------------
TRACER_SCRIPT         := $(TOP_DIR)/scripts/convert/gen_tracer.py
TRACER_OUTPUT         := $(SIM_MINISOC_BUILD_DIR)/firmware_tracer.v
# Direct use of artifacts generated by sw/include.sw.mk
FIRMWARE_DISASM_FILE  := $(SW_BUILD_DIR)/firmware.dump
FIRMWARE_SYM_FILE     := $(SW_BUILD_DIR)/firmware.sym

# ----------------------------------------------------------------------------
# Source Files
# ----------------------------------------------------------------------------

# Testbench
SIM_MINISOC_TB_SOURCE := $(wildcard $(SIM_MINISOC_DIR)/*.v)

# Hardware sources (Aggregation of all variables from sub-makefiles!)
SIM_MINISOC_HW_SOURCES := $(sort \
    $(TOP_SOURCES) \
    $(CPU_SOURCES) \
    $(BUS_SOURCES) \
    $(IMEM_SOURCES) $(DMEM_SOURCES) $(MEM_INIT_SOURCES) \
    $(UART_SOURCES) $(TIMER_SOURCES) $(GPIO_SOURCES) \
    $(PAD_SOURCES) \
    $(TRACER_OUTPUT))

# Firmware 
FIRMWARE_MEM_FILE := $(SW_BUILD_DIR)/firmware.mem

# ----------------------------------------------------------------------------
# Compilation Flags
# ----------------------------------------------------------------------------
SIM_MINISOC_IVERILOG_FLAGS := \
    -I$(SIM_MINISOC_DIR) \
    -I$(TOP_DIR)/src/common \
    -I$(SIM_MINISOC_BUILD_DIR) \
    -DFIRMWARE_PATH=\"$(FIRMWARE_MEM_FILE)\" \
    -DMINISOC_SIMULATION

SIM_LOG_FILE := $(SIM_MINISOC_BUILD_DIR)/minisoc_firmware.log
SIM_MINISOC_VVP_FLAGS := -l $(SIM_LOG_FILE)

# Target Outputs
SIM_MINISOC_OUTPUT := $(SIM_MINISOC_BUILD_DIR)/tb_minisoc.out
SIM_MINISOC_VCD    := $(SIM_MINISOC_BUILD_DIR)/minisoc_c_firmware.vcd

# ----------------------------------------------------------------------------
# Build Rules
# ----------------------------------------------------------------------------

# 1. Génération du Tracer
# Note: We depend on $(SW_DUMP) generated by the software toolchain.
$(TRACER_OUTPUT): | sw
	@mkdir -p $(dir $@)
	$(Q)touch $(FIRMWARE_SYM_FILE) 
	$(Q)echo "  [TRACER]    Generating Firmware Tracer Module"
	$(Q)python3 $(TRACER_SCRIPT) $(FIRMWARE_DISASM_FILE) $(FIRMWARE_SYM_FILE) $@

# 2. Main simulation build
# By setting $(FIRMWARE_MEM_FILE) as a dependency, Make will compile
# The C code automatically if necessary, without needing manual checking!
$(SIM_MINISOC_OUTPUT): $(SIM_MINISOC_TB_SOURCE) $(SIM_MINISOC_HW_SOURCES) $(TRACER_OUTPUT) | sw $(FIRMWARE_MEM_FILE)
	@mkdir -p $(dir $@)
	$(Q)echo "  [IVERILOG]  Compiling MiniSoC Complete System (C Firmware)"
	$(Q)$(IVERILOG) $(SIM_MINISOC_IVERILOG_FLAGS) -o $@ $(SIM_MINISOC_TB_SOURCE) $(SIM_MINISOC_HW_SOURCES)

# -------------------------------------------
# Top-level Targets
# -------------------------------------------
.PHONY: sim_minisoc.all sim_minisoc.build sim_minisoc.run sim_minisoc.wave \
        sim_minisoc.quick sim_minisoc.clean sim_minisoc.info \
        sim_minisoc.view-firmware

sim_minisoc.all: sim_minisoc.build

# Build simulation
sim_minisoc.build: sw $(SIM_MINISOC_OUTPUT)
	$(Q)echo "  [SIM-SOC]   Build complete"

# Run simulation
sim_minisoc.run: sim_minisoc.build
	$(Q)echo "  [VVP]       Running MiniSoC C Firmware Simulation..."
	$(Q)cd $(SIM_MINISOC_BUILD_DIR) && $(VVP) tb_minisoc.out $(SIM_MINISOC_VVP_FLAGS)
	$(Q)echo "  [SIM-SOC]   Simulation Complete. Log: $(SIM_LOG_FILE)"
	$(Q)echo "  [UART]      Extracting Virtual Terminal output..."
	$(Q)python3 $(TOP_DIR)/scripts/parser/parse_uart.py $(SIM_LOG_FILE)

# Run simulation with waveform capture
sim_minisoc.wave: 
	$(Q)echo "  [GTKWAVE]   Opening MiniSoC Waveform"
	$(Q)$(GTKWAVE) $(SIM_MINISOC_VCD) &

# Quick run
sim_minisoc.quick: sim_minisoc.build sim_minisoc.run 

# View firmware information
sim_minisoc.view-firmware: $(FIRMWARE_MEM_FILE)
	$(Q)echo "  [INFO]      C Firmware Information"
	$(Q)echo "Location: $(FIRMWARE_MEM_FILE)"
	$(Q)echo ""
	$(Q)echo "First 20 instructions:"
	$(Q)head -n 20 $(FIRMWARE_MEM_FILE)
	$(Q)echo ""
	$(Q)if [ -f "$(FIRMWARE_DISASM_FILE)" ]; then \
		echo "Disassembly (first 30 lines):"; \
		head -n 30 $(FIRMWARE_DISASM_FILE); \
	fi

# Show simulation information
sim_minisoc.info:
	$(Q)echo "=================================================="
	$(Q)echo "MiniSoC Complete System Simulation Info"
	$(Q)echo "=================================================="
	$(Q)echo "Build dir:      $(SIM_MINISOC_BUILD_DIR)"
	$(Q)echo "Hardware files: $(words $(SIM_MINISOC_HW_SOURCES))"
	$(Q)echo "Firmware:       $(FIRMWARE_MEM_FILE)"
	$(Q)echo "=================================================="

# Clean simulation files
sim_minisoc.clean:
	$(Q)echo "  [CLEAN]     MiniSoC Simulation artifacts"
	$(Q)rm -rf $(SIM_MINISOC_BUILD_DIR)

# -------------------------------------------
# Shortcut Targets (for main Makefile)
# -------------------------------------------
.PHONY: sim-minisoc sim-minisoc-run sim-minisoc-wave sim-minisoc-quick sim-minisoc-clean view-firmware

sim-minisoc:       sim_minisoc.build
sim-minisoc-run:   sim_minisoc.run
sim-minisoc-wave:  sim_minisoc.wave
sim-minisoc-quick: sim_minisoc.quick
sim-minisoc-clean: sim_minisoc.clean
view-firmware:     sim_minisoc.view-firmware