`timescale 1ns/1ps

// ============================================================================
// MiniSoC Complete System Testbench
// ============================================================================
// This testbench simulates the complete MiniSoC with C-generated firmware
// Firmware is automatically loaded from: ../../build/minisoc/firmware.mem
// ============================================================================

module tb_minisoc_c_firmware;

    // =======================================================================
    // PARAMETERS
    // =======================================================================
    parameter CLK_PERIOD        = 10;                               // 100 MHz clock (10ns period)
    parameter SYSTEM_CLK_FREQ   = 100_000_000;                      // 100 MHz (from system.h)
    parameter RESET_TIME        = 200;                              // 200ns reset pulse
    parameter SIM_TIMEOUT_US    = 50_000;                           // 50ms timeout (covers all demos)
    parameter SIM_TIMEOUT       = 5_000_000;

    // UART parameters
    parameter BAUD_RATE         = 115200;       
    parameter BAUD_PERIOD_NS    = SYSTEM_CLK_FREQ / BAUD_RATE;      // 8680.55ns per bit
    parameter BAUD_PERIOD       = BAUD_PERIOD_NS / CLK_PERIOD;      // 868 cycles @ 100MHz

    // MINISOC parameters
    parameter MAX_CYCLES        = 1000000;                          // Safety timeout
    parameter FIRMWARE_FILE     = "firmware.mem";
    parameter ADDR_WIDTH        = 32;
    parameter DATA_WIDTH        = 32;
    parameter IMEM_SIZE_KB      = 32;
    parameter DMEM_SIZE_KB      = 16;
    parameter DATA_SIZE_KB      = 4;
    parameter BAUD_DIV_RST      = 16'd868;                          // 115200 baud @ 100MHz
    parameter N_GPIO            = 8;

    // Timing expectations from firmware (in clock cycles)
    parameter MS_500_CYCLES     = 500_000;                          // 500ms @ 100MHz = 500,000 cycles
    parameter MS_100_CYCLES     = 100_000;                          // 100ms @ 100MHz = 100,000 cycles
    parameter BLINK_COUNT       = 10;                               // 10 blinks in demo

    // Testbench states
    parameter TB_IDLE           = 0;
    parameter TB_RESET          = 1;
    parameter TB_INIT           = 2;
    parameter TB_WAIT_MAIN      = 3;
    parameter TB_BANNER         = 4;
    parameter TB_BLINK_DEMO     = 5;
    parameter TB_MAIN_LOOP      = 6;
    parameter TB_CHECK          = 7;
    parameter TB_PASS           = 8;
    parameter TB_FAIL           = 9;


    // =======================================================================
    // INCLUDE FILES
    // =======================================================================

    // Inclusion of symbolic addresses (generated by gen_tracer.py)
    `include "firmware_tracer_symbols.vh"


    // =======================================================================
    // SIGNALS
    // =======================================================================
    
    // Clock and Reset 
    reg         clk;
    reg         rst_n;
    wire        soc_cpu_ready = dut.top_soc_inst.cpu_rst_n;

    // Testbench signals
    integer     tb_state;
    integer     cycle_count;
    integer     timeout_counter;
    reg [31:0]  start_time;
    reg [31:0]  last_state_change;

    // UART Inteface
    wire        uart_tx;
    reg         uart_rx;
    reg [7:0]   uart_rx_stim;
    reg         uart_rx_valid;
    reg [7:0]   uart_tx_buffer [0:1023];
    integer     uart_tx_idx;
    integer     uart_tx_total;
    reg         capturing_uart;
    reg [7:0]   uart_captured_byte;
    reg [10:0]  uart_capture_shift;
    integer     uart_bit_count;
    integer     uart_bit_timer;

    // GPIO Interface
    wire        gpio0_io, gpio1_io, gpio2_io, gpio3_io;
    wire        gpio4_io, gpio5_io, gpio6_io, gpio7_io;
    reg  [7:0]  gpio_dir;
    reg  [7:0]  gpio_stim;
    wire [7:0]  gpio_monitor;

    // Test tracking
    integer     log_file;
    integer     tests_passed;
    integer     tests_failed;
    reg         test_fatal_error;

    // Firmware behavior tracking
    reg         banner_printed;
    reg         blink_demo_started;
    reg         blink_demo_completed;
    integer     blink_count;
    reg         main_loop_entered;
    integer     status_counter;
    reg [31:0]  last_gpio0_change;
    reg         gpio0_state;
    integer     gpio0_transitions;

    // Expected strings from firmware
    reg [7:0]   expected_banner [0:255];
    integer     expected_banner_len;
    reg [255:0] expected_strings [0:15];
    integer     string_count;

    // Buffers for UART processing (GLobal scope for task access)
    reg [7:0]   line_buffer [0:127];
    integer     line_buffer_idx;
    reg [1023:0] temp_line_str;         // Huge vector for string compare

    // Loop variables;
    integer     i_gen;                  // General purpose iterator
    integer     j_gen;              
    
    // Signals for the Firmware Tracer
    wire [31:0]  core_pc_debug = dut.top_soc_inst.rv32i_core.fetch_stage_inst.pc_out; 
    wire [639:0] instruction_string;    // To store the instruction text (80 characters)
    reg  [31:0]  fw_checkpoint;         // To follow the boot process
    reg          bss_loop_once;
    reg          data_loop_once;
    reg          boot_sequence_once;


    // =======================================================================
    // DUT INSTANTIATION
    // =======================================================================
    
    // Instance of the tracing module (Giant Lookup Table)
    firmware_tracer tracer_inst (
        .pc       (core_pc_debug),
        .mnemonic (instruction_string)
    );

    // DUT
    mini_rv32i_top #(
        .FIRMWARE_FILE  (FIRMWARE_FILE  ),
        .ADDR_WIDTH     (ADDR_WIDTH     ),
        .DATA_WIDTH     (DATA_WIDTH     ),
        .IMEM_SIZE_KB   (IMEM_SIZE_KB   ),
        .DMEM_SIZE_KB   (DMEM_SIZE_KB   ),
        .DATA_SIZE_KB   (DATA_SIZE_KB   ),
        .BAUD_DIV_RST   (BAUD_DIV_RST   ),
        .N_GPIO         (N_GPIO         )
    ) dut (
        .clk        (clk),
        .rst_n      (rst_n),
        .uart_rx    (uart_rx),
        .uart_tx    (uart_tx),
        .gpio0_io   (gpio0_io),
        .gpio1_io   (gpio1_io),
        .gpio2_io   (gpio2_io),
        .gpio3_io   (gpio3_io),
        .gpio4_io   (gpio4_io),
        .gpio5_io   (gpio5_io),
        .gpio6_io   (gpio6_io),
        .gpio7_io   (gpio7_io)
    );

    
    // =======================================================================
    // GPIO MODELING (bidirectional)
    // =======================================================================
    assign gpio0_io = gpio_dir[0] ? 1'bz : gpio_stim[0];
    assign gpio1_io = gpio_dir[1] ? 1'bz : gpio_stim[1];
    assign gpio2_io = gpio_dir[2] ? 1'bz : gpio_stim[2];
    assign gpio3_io = gpio_dir[3] ? 1'bz : gpio_stim[3];
    assign gpio4_io = gpio_dir[4] ? 1'bz : gpio_stim[4];
    assign gpio5_io = gpio_dir[5] ? 1'bz : gpio_stim[5];
    assign gpio6_io = gpio_dir[6] ? 1'bz : gpio_stim[6];
    assign gpio7_io = gpio_dir[7] ? 1'bz : gpio_stim[7];

    assign gpio_monitor[0] = gpio_dir[0] ? gpio0_io : 1'b0;
    assign gpio_monitor[1] = gpio_dir[1] ? gpio1_io : 1'b0;
    assign gpio_monitor[2] = gpio_dir[2] ? gpio2_io : 1'b0;
    assign gpio_monitor[3] = gpio_dir[3] ? gpio3_io : 1'b0;
    assign gpio_monitor[4] = gpio_dir[4] ? gpio4_io : 1'b0;
    assign gpio_monitor[5] = gpio_dir[5] ? gpio5_io : 1'b0;
    assign gpio_monitor[6] = gpio_dir[6] ? gpio6_io : 1'b0;
    assign gpio_monitor[7] = gpio_dir[7] ? gpio7_io : 1'b0;


    // =======================================================================
    // CLOCK GENERATION
    // =======================================================================
    initial begin
        clk = 0;
        forever #(CLK_PERIOD/2) clk = ~clk;
    end


    // =======================================================================
    // RESET AND INITIALIZATION
    // =======================================================================
    initial begin
        // Open Log file
        log_file = $fopen("minisoc_firmware.log", "w");

        // Initialize signals
        rst_n                   = 0;
        tb_state                = TB_RESET;
        cycle_count             = 0;
        tests_passed            = 0;
        tests_failed            = 0;
        test_fatal_error        = 0;
        
        // UART init
        uart_rx                 = 1'b1;
        uart_tx_total           = 0;
        line_buffer_idx         = 0;
        
        // GPIO init
        gpio_dir                = 8'h00;
        gpio_stim               = 8'h00;
        
        // Firmware tracking
        banner_printed          = 0;
        blink_demo_started      = 0;
        blink_demo_completed    = 0;
        blink_count             = 0;
        main_loop_entered       = 0;
        status_counter          = 0;
        last_gpio0_change       = 0;
        gpio0_state             = 0;
        gpio0_transitions       = 0;
        bss_loop_once           = 0;
        data_loop_once          = 0;
        boot_sequence_once      = 0;
        
        // Load strings
        load_expected_strings();
        
        // Start simulation info
        #100;
        $display("==================================================");
        $display("MINI RV32I SoC FIRMWARE TESTBENCH");
        $display("==================================================");
        $display("System Clock: %0d MHz", SYSTEM_CLK_FREQ/1000000);
        
        // Release Reset
        #(RESET_TIME);
        rst_n                   = 1;
        start_time              = 0;
        last_state_change       = 0;
        $display("[TB] Reset released");
    end


    // =======================================================================
    // CYCLE COUNTER 
    // =======================================================================
    always @(posedge clk) begin
        cycle_count <= cycle_count + 1;
    end


    // =======================================================================
    // TESTBENCH STATE MACHINE
    // =======================================================================
    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            tb_state        <= TB_RESET;
            tests_passed    <= 0;
            tests_failed    <= 0;
        end else begin

            // GLOBAL TIMEOUT CHECK 
            if (cycle_count > SIM_TIMEOUT) begin
                $display("\n==================================================");
                $display("[FATAL]: Simulation Global timeout!");
                tb_state <= TB_FAIL;
            end 
            else begin 
                // MAIN STATE MACHINE
                case (tb_state)
                    
                    // Wait for the testbench to release the external reset
                    // Wait for "RESET AND INITIALIZATION" block to finish
                    TB_RESET: begin
                        if (rst_n) begin
                            tb_state <= TB_INIT;
                            last_state_change = cycle_count;
                            $display("[TB] External Reset Released. Waiting for SoC Init...");
                        end
                    end

                    // Wait for internal SoC to release the CPU
                    TB_INIT: begin
                        if (soc_cpu_ready) begin
                            verify_firmware_loaded();
                            tb_state <= TB_WAIT_MAIN;
                            last_state_change = cycle_count;
                            $display("[TB] SoC Initialization Complete. CPU Running.");
                        end

                        // State-specific timeout (e.g., if memory init hangs)
                        if ((cycle_count - last_state_change) > 100_000) begin
                            $display("[ERROR]: SoC Init Timed Out!");
                            tb_state <= TB_FAIL;
                        end
                    end


                    // Precise verification based on the main symbol address
                    TB_WAIT_MAIN: begin
                        if (core_pc_debug == SYM_MAIN) begin
                            $display("[TB] Firmware reached main() successfully!");
                            tb_state <= TB_BANNER; 
                            last_state_change = cycle_count;
                        end

                        // Security timeout
                        if ((cycle_count - last_state_change) > 50_000) begin
                            $display("[ERROR] Boot timeout! Stuck at PC: %h (%s)", core_pc_debug, instruction_string);
                            tb_state <= TB_FAIL;
                        end
                    end

                    TB_BANNER: begin
                        if (banner_printed) begin
                            tb_state <= TB_BLINK_DEMO;
                            last_state_change = cycle_count;
                            $display("[TB] Banner Verified");
                            check_banner_content();
                        end
                        if ((cycle_count - last_state_change) > 2_000_000) begin
                            $display("[TB] TIMEOUT: Waiting for banner");
                            tb_state <= TB_FAIL;
                        end
                    end

                    TB_BLINK_DEMO: begin
                        if (blink_count >= BLINK_COUNT) begin
                            tb_state <= TB_MAIN_LOOP;
                            last_state_change = cycle_count;
                            $display("[TB] Blink Demo Done");
                        end
                        // Timeout logic
                        if ((cycle_count - last_state_change) > 2_000_000) begin
                            // If we haven't seen blinks, move on but log error
                            $display("[TB] TIMEOUT: Blink Demo");
                            tb_state <= TB_MAIN_LOOP;
                        end
                    end

                    TB_MAIN_LOOP: begin
                        if (status_counter >= 3) begin
                            tb_state <= TB_CHECK;
                        end
                        if ((cycle_count - last_state_change) > 2_000_000) begin
                            tb_state <= TB_CHECK;
                        end
                    end

                    TB_CHECK: begin
                        verify_overall_behavior();
                        tb_state <= (tests_failed == 0) ? TB_PASS : TB_FAIL;
                    end

                    TB_PASS: begin
                        tests_passed <= 1;
                        $display("\n*** TEST PASSED ***");
                        $finish;
                    end

                    TB_FAIL: begin
                        tests_failed <= 1;
                        $display("\n*** TEST FAILED ***");
                        $finish(1);
                    end 
                endcase
            end 
        end
    end 


    // =======================================================================
    // VERIFY FIRMWARE IS LOADED
    // =======================================================================
    task verify_firmware_loaded;
        begin
            // Check first few instructions in IMEM
            $display("[FIRMWARE_VERIFY] IMEM[0] = %h (should be first instruction)", 
                    dut.top_soc_inst.imem_inst.imem_inst.mem[0]);
            $display("[FIRMWARE_VERIFY] IMEM[1] = %h", 
                    dut.top_soc_inst.imem_inst.imem_inst.mem[1]);
            $display("[FIRMWARE_VERIFY] IMEM[2] = %h", 
                    dut.top_soc_inst.imem_inst.imem_inst.mem[2]);
            
            $fdisplay(log_file, "[FIRMWARE_VERIFY] IMEM[0] = %h", 
                    dut.top_soc_inst.imem_inst.imem_inst.mem[0]);
            $fdisplay(log_file, "[FIRMWARE_VERIFY] IMEM[1] = %h", 
                    dut.top_soc_inst.imem_inst.imem_inst.mem[1]);
            $fdisplay(log_file, "[FIRMWARE_VERIFY] IMEM[2] = %h", 
                    dut.top_soc_inst.imem_inst.imem_inst.mem[2]);
            
            // Check if instructions look valid
            if (dut.top_soc_inst.imem_inst.imem_inst.mem[0] === 32'hxxxxxxxx) begin
                $display("[FIRMWARE_VERIFY] ERROR: ❌ IMEM[0] is uninitialized!");
                $fdisplay(log_file, "[FIRMWARE_VERIFY] ERROR: ❌ IMEM[0] is uninitialized!");
            end else begin
                $display("[FIRMWARE_VERIFY] ✅ IMEM appears to be initialized");
                $fdisplay(log_file, "[FIRMWARE_VERIFY] ✅ IMEM appears to be initialized");
            end
        end
    endtask


    // =======================================================================
    // EXECUTION FLOW MONITOR
    // =======================================================================

    // CPU Context 
    reg [1023:0] current_context = "Unknown";

    always @(core_pc_debug) begin
        case (core_pc_debug)
            SYM__START:    begin
                if (!boot_sequence_once) begin
                    current_context = "Boot sequence";
                    $display("[FW_MON] 🚀 Boot sequence started (<_start>) at %t", $time);
                    boot_sequence_once = 1;
                end
                
            end


            SYM_BSS_LOOP:  begin
                if (!bss_loop_once) begin
                    current_context = "BSS Loop";
                    $display("[FW_MON] 🧹 Initializing .bss section (<bss_loop>) at %t", $time); 
                    bss_loop_once = 1;
                end
            end
            
            
            SYM_DATA_LOOP: begin
                if (!data_loop_once) begin
                    current_context = "DATA Loop";
                    $display("[FW_MON] 💾 Copying .data section (<data_loop>) at %t", $time);
                    data_loop_once = 1;
                end
            end
            

            SYM_MAIN: begin
                current_context = "Main Entry";
                $display("[FW_MON] ✅ Jump to main() application at %t", $time);
                check_data_integrity(); 
            end


            SYM_SYSTEM_INIT: begin
                current_context = "SYSTEM INIT";
                $display("[FW_MON] ✅ Jump to system_init() function at %t", $time);
            end
            

            SYM_PERIPHERAL_INIT: begin
                current_context = "Periph INIT Process";
                $display("[FW_MON] ✅ Jump to peripheral_init() - Initialize UART/TIMER/GPIO function at %t", $time);
            end


            SYM_PERIPHERAL_IS_INITIALIZED: begin
                current_context = "Periph INIT CHECK";
                $display("[FW_MON] ✅ Jump to peripheral_is_initialized() - Check if UART/TIMER/GPIO function at %t", $time);
            end


            SYM_UART_INIT: begin
                current_context = "Periph UART INIT";
                $display("[FW_MON] ✅ Jump to peripherals_init_safe() - uart_init() function at %t", $time);
            end


            SYM_UART_CONFIGURE: begin
                current_context = "Periph UART CONFIG";
                $display("[FW_MON] ✅ Jump to peripherals_init_safe() - uart_configure() function at %t", $time);
            end


            SYM_UART_DEINIT: begin
                current_context = "Periph UART DEINIT";
                $display("[FW_MON] ✅ Jump to peripherals_init_safe() - uart_deinit() function at %t", $time);
            end


            SYM_GPIO_INIT: begin
                current_context = "Periph GPIO INIT";
                $display("[FW_MON] ✅ Jump to peripherals_init_safe() - gpio_init() function at %t", $time);
            end


            SYM_GPIO_CONFIGURE_PIN: begin
                current_context = "Periph GPIO CONFIG PIN";
                $display("[FW_MON] ✅ Jump to peripherals_init_safe() - gpio_configure_pin() function at %t", $time);
            end

            SYM_GPIO_DEINIT: begin
                current_context = "Periph GPIO DEINIT";
                $display("[FW_MON] ✅ Jump to peripherals_init_safe() - gpio_deinit() function at %t", $time);
            end


            SYM_TIMER_INIT: begin
                current_context = "Periph TIMER INIT";
                $display("[FW_MON] ✅ Jump to peripherals_init_safe() - timer_init() function at %t", $time);
            end


            SYM_TIMER_DEINIT: begin
                current_context = "Periph TIMER DEINIT";
                $display("[FW_MON] ✅ Jump to peripherals_init_safe() - timer_deinit() function at %t", $time);
            end


            SYM_SYSTEM_INIT_WITH_TIMER_SAFE: begin
                current_context = "System Timer Init with Safety function";
                $display("[FW_MON] ✅ Jump to peripherals_init_safe() - system_init_with_timer_safe() function at %t", $time);
            end


            SYM_APP_PRINT_STRING: begin
                current_context = "System Print with Safety function";
                $display("[FW_MON] ✅ Jump to print_string_safe() function - Display_system_info_safe/ at %t", $time);
            end

        endcase
    end

    task check_data_integrity;
        integer i;
        reg [31:0] addr;
        reg [31:0] ram_val;
        reg [31:0] expected_val;
        begin
            $display("\n[TB][VERIFY] Checking .data integrity...");
            
            // On utilise les symboles générés pour connaître la plage exacte
            // SYM__SDATA = début RAM (0x10000000)
            // SYM__EDATA = fin RAM (0x10000004 ou plus)
            // SYM_VERIFICATION_CANARY = Adresse de la variable (0x10000000)
            
            if (SYM__EDATA <= SYM__SDATA) begin
                $display("[TB][WARNING] .data section is empty (Size 0). Nothing to verify.");
            end else begin
                // Vérification spécifique de notre CANARY
                // On lit directement dans le tableau mémoire du modèle Verilog (Backdoor access)
                
                // Note : Ajustez le chemin 'dmem_inst.mem' selon votre hiérarchie
                // index = (Adresse - Base) / 4
                ram_val = dut.top_soc_inst.dmem_inst.dmem_inst.mem[(SYM_VERIFICATION_CANARY - 32'h10000000)/4];
                
                // Valeur attendue : 0xCAFEBABE
                if (ram_val === 32'hCAFEBABE) begin
                    $display("[TB][PASS] ✅ Verification Canary found: %h at address %h", ram_val, SYM_VERIFICATION_CANARY);
                end else begin
                    $display("[TB][FAIL] ❌ Data Mismatch! Addr: %h, Read: %h, Expected: CAFEBABE", SYM_VERIFICATION_CANARY, ram_val);
                    $stop; // Arrêt simulation sur erreur critique
                end
            end
            $display("------------------------------------------------------------\n");
        end
    endtask

    
    // =======================================================================
    // UART RX MONITOR 
    // =======================================================================
    initial begin
        forever begin
            // 1. Wait for Start bit (Falling Edge)
            @(negedge uart_tx);

            // 2. Wait hakf bit period to sample middle of start bit
            #(BAUD_PERIOD * CLK_PERIOD / 2);

            if (uart_tx == 0) begin
                // 3. Sample 8 data bits
                uart_captured_byte = 0;
                for (i_gen = 0; i_gen < 8; i_gen++) begin
                    #(BAUD_PERIOD * CLK_PERIOD);
                    uart_captured_byte[i_gen] = uart_tx;
                end

                // 4. Wait for stop bit
                #(BAUD_PERIOD * CLK_PERIOD);

                // 5. Store and Process
                uart_tx_buffer[uart_tx_total] = uart_captured_byte;
                uart_tx_total = uart_tx_total + 1;

                process_uart_byte(uart_captured_byte);
            end
        end
    end


    // =======================================================================
    // UART PROCESSING TASKS
    // =======================================================================
    task process_uart_byte;
        input [7:0] byte_data;
        begin
            // Echo character to console 
            if (byte_data >= 8'h20 && byte_data <= 8'h7E) 
                $write("%c", byte_data);
            else if (byte_data == 8'h0D || byte_data == 8'h0A)
                $write("\n");
            else 
                $write(".");

            // Line buffering
            if (byte_data == 8'h0D || byte_data == 8'h0A) begin // \r or \n
                if (line_buffer_idx > 0) begin
                    check_uart_line(); // Checks global line_buffer
                    line_buffer_idx = 0;
                end
            end else begin
                line_buffer[line_buffer_idx] = byte_data;
                line_buffer_idx = line_buffer_idx + 1;
                if (line_buffer_idx >= 127) line_buffer_idx = 0;
            end
            
            // Immediate char checks
            if (byte_data == 8'h2E) begin // '.'
                if (blink_demo_started && !blink_demo_completed) begin
                    blink_count = blink_count + 1;
                end
            end
        end
    endtask


    // ======================================================================
    // CHECK UART LINE
    // ======================================================================
    task check_uart_line;
        integer k;
        reg [255:0] current_line_packed;
        begin
            // Pack the buffer into a single wide register for comparison
            current_line_packed = 0;
            
            // Note: We pack from left to right to match string literals in Verilog
            // e.g. "Hello" -> H is MSB in string literal context usually, 
            // but here we construct based on the expected_strings format.
            // Let's use a simpler match approach: 
            
            // Clear temp
            temp_line_str = 0;
            
            // Convert byte array to bit vector for comparison
            // We limit to 32 chars to match expected_strings width
            for (k = 0; k < 32; k = k + 1) begin
                if (k < line_buffer_idx)
                    current_line_packed[ (31-k)*8 +: 8 ] = line_buffer[k];
                else
                    current_line_packed[ (31-k)*8 +: 8 ] = 0;
            end

            // Compare against expected strings
            // 1. Banner Start
            if (current_line_packed == expected_strings[1]) begin
                $display("\n[CHECK] Firmware Start Detected");
                banner_printed = 1;
            end
            // 2. Clock
            else if (current_line_packed == expected_strings[3]) begin
                tests_passed = tests_passed + 1;
            end
            // 3. Blink Start
            else if (current_line_packed == expected_strings[7]) begin
                blink_demo_started = 1;
                $display("\n[CHECK] Blink Demo Started");
            end
            // 4. Blink End
            else if (current_line_packed == expected_strings[8]) begin
                blink_demo_completed = 1;
            end
            // 5. Main Loop
            else if (current_line_packed == expected_strings[9]) begin
                main_loop_entered = 1;
            end
            
            // Special partial match for counter
            // (Verilog partial string matching is tedious, simplified here)
            if (line_buffer_idx > 25) begin
                // Logic to detect "System running... Counter:"
                // Simplified: just assume if main loop entered and length is right
                if (main_loop_entered) status_counter = status_counter + 1;
            end
        end
    endtask

    // ======================================================================
    // GPIO MONITORING
    // ======================================================================
    always @(gpio_monitor) begin
        if (cycle_count > 100) begin
            // Only monitor bit 0
            if (gpio_monitor[0] != gpio0_state) begin
                gpio0_transitions = gpio0_transitions + 1;
                
                // Period check
                if (last_gpio0_change > 0) begin
                    // integer period = cycle_count - last_gpio0_change;
                    // Add specific checks here if needed
                end
                
                gpio0_state = gpio_monitor[0];
                last_gpio0_change = cycle_count;
            end
        end
    end

    // ======================================================================
    // HELPERS
    // ======================================================================
    task load_expected_strings;
        begin
            // Verilog-2001 style string assignment to packed arrays
            // Note: Strings are right-padded with zeros if shorter than reg width
            // Ensure the string literal matches the packing logic in check_uart_line
            
            // "Mini RV32I SoC Firmware Started\r" (32 chars approx)
            expected_strings[1] = "Mini RV32I SoC Firmware Started\r";
            
            expected_strings[3] = "System Clock: 100000000 Hz\r\0\0\0\0\0"; // Padding
            
            expected_strings[7] = "LED Blink Demo Started\r\0\0\0\0\0\0\0\0\0";
            expected_strings[8] = "LED Blink Demo Completed\r\0\0\0\0\0\0\0";
            expected_strings[9] = "All demos completed. Entering ma"; // Truncated to 32 chars
        end
    endtask

    task check_banner_content;
        begin
            if (banner_printed) tests_passed = tests_passed + 1;
            if (blink_demo_started) tests_passed = tests_passed + 1;
        end
    endtask

    task verify_overall_behavior;
        begin
            $display("--------------------------------");
            $display("Passed: %0d, Failed: %0d", tests_passed, tests_failed);
            
            if (uart_tx_total > 10) $display("[PASS] UART Activity Detected");
            else tests_failed = tests_failed + 1;
            
            if (gpio0_transitions > 4) $display("[PASS] GPIO Activity Detected");
            else tests_failed = tests_failed + 1;
            
            if (main_loop_entered) $display("[PASS] Main Loop Reached");
            else tests_failed = tests_failed + 1;
        end
    endtask


    // =======================================================================
    // WAVEFORM DUMP
    // =======================================================================
    initial begin
        $dumpfile("minisoc_c_firmware.vcd");
        $dumpvars(0, tb_minisoc_c_firmware);
        // Dump all hierarchy levels
        $dumpvars(1, dut);
        $dumpvars(2, dut.top_soc_inst);
        $dumpvars(3, dut.top_soc_inst.rv32i_core);
        $dumpvars(3, dut.top_soc_inst.imem_inst);
        $dumpvars(3, dut.top_soc_inst.dmem_inst);
        $dumpvars(3, dut.top_soc_inst.uart_inst);
        $dumpvars(3, dut.top_soc_inst.gpio_inst);
        $dumpvars(3, dut.top_soc_inst.timer_inst);
        $display("[TB] Waveform dumping enabled: minisoc_c_firmware.vcd");
    end

    
    
    
endmodule