`timescale 1ns/1ps

// ============================================================================
// MiniSoC Complete System Testbench
// ============================================================================
// This testbench simulates the complete MiniSoC with C-generated firmware
// Firmware is automatically loaded from: ../../build/minisoc/firmware.mem
// ============================================================================

// Use the macro passed via the Makefile; otherwise, the default value will be used.
`ifndef FIRMWARE_PATH
    `define FIRMWARE_PATH "firmware.mem"
`endif


module tb_minisoc_c_firmware;

    // =======================================================================
    // PARAMETERS
    // =======================================================================
    parameter CLK_PERIOD        = 10;                               // 100 MHz clock (10ns period)
    parameter SYSTEM_CLK_FREQ   = 100_000_000;                      // 100 MHz (from system.h)
    parameter RESET_TIME        = 200;                              // 200ns reset pulse
    parameter SIM_TIMEOUT_US    = 50_000;                           // 50ms timeout (covers all demos)
    parameter SIM_TIMEOUT       = 15_000_000;

    // UART parameters
    parameter BAUD_RATE         = 115200;       
    parameter BAUD_PERIOD       = SYSTEM_CLK_FREQ / BAUD_RATE;      // 868 cycles @ 100MHz
    parameter BAUD_PERIOD_NS    = (BAUD_PERIOD * CLK_PERIOD);       // 8680.55ns per bit 

    // MINISOC parameters
    parameter MAX_CYCLES        = 1000000;                          // Safety timeout
    parameter FIRMWARE_FILE     = `FIRMWARE_PATH;
    parameter ADDR_WIDTH        = 32;
    parameter DATA_WIDTH        = 32;
    parameter IMEM_SIZE_KB      = 32;
    parameter DMEM_SIZE_KB      = 16;
    parameter DATA_SIZE_KB      = 4;
    parameter BAUD_DIV_RST      = 16'd868;                          // 115200 baud @ 100MHz
    parameter N_GPIO            = 8;

    // Timing expectations from firmware (in clock cycles)
    parameter MS_500_CYCLES     = 500_000;                          // 500ms @ 100MHz = 500,000 cycles
    parameter MS_100_CYCLES     = 100_000;                          // 100ms @ 100MHz = 100,000 cycles
    parameter BLINK_COUNT       = 10;                               // 10 blinks in demo

    // Testbench states
    parameter TB_RESET          = 0;
    parameter TB_INIT           = 1;
    parameter TB_WAIT_MAIN      = 2;
    parameter TB_RUNNING        = 3;
    parameter TB_CHECK          = 4;
    parameter TB_PASS           = 5;
    parameter TB_FAIL           = 6;


    // =======================================================================
    // INCLUDE FILES
    // =======================================================================

    // Inclusion of symbolic addresses (generated by gen_tracer.py)
    `include "firmware_tracer_symbols.vh"


    // =======================================================================
    // SIGNALS
    // =======================================================================
    
    // Clock and Reset 
    reg         clk;
    reg         rst_n;
    wire        soc_cpu_ready = dut.top_soc_inst.cpu_rst_n;

    // Testbench signals
    integer     tb_state;
    integer     cycle_count;
    integer     timeout_counter;
    reg [31:0]  start_time;
    reg [31:0]  last_state_change;

    // CPU Pipeline check
    integer     cpu_trace_log;
    wire [ADDR_WIDTH-1:0]   fetch_pc        = dut.top_soc_inst.rv32i_core.fetch_stage_inst.pc;
    wire [ADDR_WIDTH-1:0]   decode_pc       = dut.top_soc_inst.rv32i_core.decode_stage_inst.pc_in;
    wire [ADDR_WIDTH-1:0]   execute_pc      = dut.top_soc_inst.rv32i_core.execute_stage_inst.pc_in;
    wire [ADDR_WIDTH-1:0]   mem_pc          = dut.top_soc_inst.rv32i_core.mem_stage_inst.pc_in;
    wire [ADDR_WIDTH-1:0]   writeback_pc    = dut.top_soc_inst.rv32i_core.writeback_stage_inst.pc_in;
    wire [DATA_WIDTH-1:0]   fetch_instr     = dut.top_soc_inst.rv32i_core.fetch_stage_inst.wbm_imem_data_read;
    wire [DATA_WIDTH-1:0]   decode_instr    = dut.top_soc_inst.rv32i_core.decode_stage_inst.instr_in;
    wire [DATA_WIDTH-1:0]   execute_instr   = dut.top_soc_inst.rv32i_core.execute_stage_inst.instr_in;
    wire [DATA_WIDTH-1:0]   mem_instr       = dut.top_soc_inst.rv32i_core.mem_stage_inst.instr_in;
    wire [DATA_WIDTH-1:0]   writeback_instr = dut.top_soc_inst.rv32i_core.writeback_stage_inst.instr_in;

    // UART Inteface
    wire        uart_tx;
    reg         uart_rx;
    reg [7:0]   uart_tx_buffer [0:1023];
    integer     uart_tx_total;
    reg [7:0]   uart_captured_byte;

    // GPIO Interface
    wire        gpio0_io, gpio1_io, gpio2_io, gpio3_io;
    wire        gpio4_io, gpio5_io, gpio6_io, gpio7_io;
    reg  [7:0]  gpio_dir;
    reg  [7:0]  gpio_stim;
    wire [7:0]  gpio_monitor;

    // Test tracking
    integer     log_file;
    integer     tests_passed;
    integer     tests_failed;
    reg         test_fatal_error;

    // Firmware behavior tracking
    reg [31:0]  last_gpio0_change;
    reg         gpio0_state;
    integer     gpio0_transitions;

    // Loop variables;
    integer     i_gen;                  // General purpose iterator
    
    // Signals for the Firmware Tracer
    wire [31:0]  core_pc_debug = dut.top_soc_inst.rv32i_core.fetch_stage_inst.pc_out; 
    wire [639:0] instruction_string;    // To store the instruction text (80 characters)
    reg  [31:0]  fw_checkpoint;         // To follow the boot process
    reg          bss_loop_once;
    reg          data_loop_once;
    reg          boot_sequence_once;


    // =======================================================================
    // DUT INSTANTIATION
    // =======================================================================
    
    // Instance of the tracing module (Giant Lookup Table)
    firmware_tracer tracer_inst (
        .pc       (core_pc_debug),
        .mnemonic (instruction_string)
    );

    // DUT
    mini_rv32i_top #(
        .FIRMWARE_FILE  (FIRMWARE_FILE  ),
        .ADDR_WIDTH     (ADDR_WIDTH     ),
        .DATA_WIDTH     (DATA_WIDTH     ),
        .IMEM_SIZE_KB   (IMEM_SIZE_KB   ),
        .DMEM_SIZE_KB   (DMEM_SIZE_KB   ),
        .DATA_SIZE_KB   (DATA_SIZE_KB   ),
        .BAUD_DIV_RST   (BAUD_DIV_RST   ),
        .N_GPIO         (N_GPIO         )
    ) dut (
        .clk        (clk),
        .rst_n      (rst_n),
        .uart_rx    (uart_rx),
        .uart_tx    (uart_tx),
        .gpio0_io   (gpio0_io),
        .gpio1_io   (gpio1_io),
        .gpio2_io   (gpio2_io),
        .gpio3_io   (gpio3_io),
        .gpio4_io   (gpio4_io),
        .gpio5_io   (gpio5_io),
        .gpio6_io   (gpio6_io),
        .gpio7_io   (gpio7_io)
    );

    
    // =======================================================================
    // GPIO MODELING (bidirectional)
    // =======================================================================
    assign gpio0_io = gpio_dir[0] ? 1'bz : gpio_stim[0];
    assign gpio1_io = gpio_dir[1] ? 1'bz : gpio_stim[1];
    assign gpio2_io = gpio_dir[2] ? 1'bz : gpio_stim[2];
    assign gpio3_io = gpio_dir[3] ? 1'bz : gpio_stim[3];
    assign gpio4_io = gpio_dir[4] ? 1'bz : gpio_stim[4];
    assign gpio5_io = gpio_dir[5] ? 1'bz : gpio_stim[5];
    assign gpio6_io = gpio_dir[6] ? 1'bz : gpio_stim[6];
    assign gpio7_io = gpio_dir[7] ? 1'bz : gpio_stim[7];

    assign gpio_monitor[0] = gpio0_io;
    assign gpio_monitor[1] = gpio1_io;
    assign gpio_monitor[2] = gpio2_io;
    assign gpio_monitor[3] = gpio3_io;
    assign gpio_monitor[4] = gpio4_io;
    assign gpio_monitor[5] = gpio5_io;
    assign gpio_monitor[6] = gpio6_io;
    assign gpio_monitor[7] = gpio7_io;


    // =======================================================================
    // CLOCK GENERATION
    // =======================================================================
    initial begin
        clk = 0;
        forever #(CLK_PERIOD/2) clk = ~clk;
    end


    // =======================================================================
    // CYCLE COUNTER 
    // =======================================================================
    always @(posedge clk) begin
        cycle_count <= cycle_count + 1;
    end


    // =======================================================================
    // RESET AND INITIALIZATION
    // =======================================================================
    initial begin
        // Open Log file
        log_file = $fopen("minisoc_firmware.log");
        log_file = log_file | 1;

        cpu_trace_log = $fopen("minisoc_firmware_cpu_trace.log", "w");

        $fdisplay(log_file, "==================================================");
        $fdisplay(log_file, "MINI RV32I SoC FIRMWARE TESTBENCH");
        $fdisplay(log_file, "Loading Firmware: %s", FIRMWARE_FILE);
        $fdisplay(log_file, "==================================================");


        // Initialize signals
        rst_n                   = 0;
        tb_state                = TB_RESET;
        cycle_count             = 0;
        tests_passed            = 0;
        tests_failed            = 0;
        test_fatal_error        = 0;
        
        // UART init
        uart_rx                 = 1'b1;
        uart_tx_total           = 0;
        
        // GPIO init
        gpio_dir                = 8'hFF;    // TB listens, CPU commands
        gpio_stim               = 8'h00;
        
        // Firmware tracking
        last_gpio0_change       = 0;
        gpio0_state             = 0;
        gpio0_transitions       = 0;
        bss_loop_once           = 0;
        data_loop_once          = 0;
        boot_sequence_once      = 0;
        
        // Start simulation info
        #100;
        $fdisplay(log_file, "==================================================");
        $fdisplay(log_file, "MINI RV32I SoC FIRMWARE TESTBENCH");
        $fdisplay(log_file, "==================================================");
        $fdisplay(log_file, "System Clock: %0d MHz", (SYSTEM_CLK_FREQ/1000000));
        
        // Release Reset
        #(RESET_TIME);
        rst_n                   = 1;
        start_time              = 0;
        last_state_change       = 0;
        $fdisplay(log_file, "[TB] Reset released");
    end


    // =======================================================================
    // TESTBENCH STATE MACHINE
    // =======================================================================
    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            tb_state        <= TB_RESET;
            tests_passed    <= 0;
            tests_failed    <= 0;
        end else begin

            // GLOBAL TIMEOUT CHECK 
            if (cycle_count > SIM_TIMEOUT) begin
                $fdisplay(log_file, "\n==================================================");
                $fdisplay(log_file, "[FATAL]: Simulation Global timeout!");
                tb_state <= TB_FAIL;
            end 
            else begin 
                // MAIN STATE MACHINE
                case (tb_state)
                    
                    // Wait for the testbench to release the external reset
                    // Wait for "RESET AND INITIALIZATION" block to finish
                    TB_RESET: begin
                        if (rst_n) begin
                            tb_state <= TB_INIT;
                            last_state_change = cycle_count;
                            $fdisplay(log_file, "\n[TB] External Reset Released. Waiting for SoC Init...");
                        end
                    end

                    // Wait for internal SoC to release the CPU
                    TB_INIT: begin
                        if (soc_cpu_ready) begin
                            verify_firmware_loaded();
                            tb_state <= TB_WAIT_MAIN;
                            last_state_change = cycle_count;
                            $fdisplay(log_file, "\n[TB] SoC Initialization Complete. CPU Running. Waiting for main()...");
                        end

                        // State-specific timeout (e.g., if memory init hangs)
                        if ((cycle_count - last_state_change) > 100_000) begin
                            $fdisplay(log_file, "\n[ERROR]: SoC Init Timed Out!");
                            tb_state <= TB_FAIL;
                        end
                    end


                    // Precise verification based on the main symbol address
                    TB_WAIT_MAIN: begin
                        if (core_pc_debug == SYM_MAIN) begin
                            $fdisplay(log_file, "\n[TB] Firmware reached main() successfully! Letting it run...");
                            tb_state <= TB_RUNNING; 
                            last_state_change = cycle_count;
                        end

                        // Security timeout
                        if ((cycle_count - last_state_change) > 50_000) begin
                            $fdisplay(log_file, "\n[ERROR] Boot timeout! Stuck at PC: %h (%s)", core_pc_debug, instruction_string);
                            tb_state <= TB_FAIL;
                        end
                    end

                    TB_RUNNING: begin
                        // Left firmware running during N cycles to see UART/BLINK demo
                        // Or if a specific function is reached (e.g., SYM_END_DEMO)
                        if ((cycle_count - last_state_change) > 10_000_000) begin 
                            $fdisplay(log_file, "\n[TB] Simulation time completed. Proceeding to checks.");
                            tb_state <= TB_CHECK;
                        end
                    end

                    TB_CHECK: begin
                        verify_overall_behavior();
                        tb_state <= (tests_failed == 0) ? TB_PASS : TB_FAIL;
                    end

                    TB_PASS: begin
                        tests_passed <= 1;
                        $fdisplay(log_file, "\n*** TEST PASSED ***");
                        $finish;
                    end

                    TB_FAIL: begin
                        tests_failed <= 1;
                        $fdisplay(log_file, "\n*** TEST FAILED ***");
                        $finish(1);
                    end 
                endcase
            end 
        end
    end 


    // =======================================================================
    // VERIFY FIRMWARE IS LOADED
    // =======================================================================
    task verify_firmware_loaded;
        begin
            // Check first few instructions in IMEM
            $fdisplay(log_file, "[FIRMWARE_VERIFY] IMEM[0] = %h (should be first instruction)", 
                    dut.top_soc_inst.imem_inst.imem_inst.mem[0]);
            $fdisplay(log_file, "[FIRMWARE_VERIFY] IMEM[1] = %h", 
                    dut.top_soc_inst.imem_inst.imem_inst.mem[1]);
            $fdisplay(log_file, "[FIRMWARE_VERIFY] IMEM[2] = %h", 
                    dut.top_soc_inst.imem_inst.imem_inst.mem[2]);
            
            
            // Check if instructions look valid
            if (dut.top_soc_inst.imem_inst.imem_inst.mem[0] === 32'hxxxxxxxx) begin
                $fdisplay(log_file, "[FIRMWARE_VERIFY] ERROR: ❌ IMEM[0] is uninitialized!");
            end else begin
                $fdisplay(log_file, "[FIRMWARE_VERIFY] ✅ IMEM appears to be initialized");
            end
        end
    endtask


    // =======================================================================
    // EXECUTION FLOW MONITOR
    // =======================================================================

    // CPU Context 
    reg [1023:0] current_context = "Unknown";

    always @(core_pc_debug) begin
        case (core_pc_debug)
            SYM__START:    begin
                if (!boot_sequence_once) begin
                    current_context = "Boot sequence";
                    $fdisplay(log_file, "\n[FW_MON] 🚀 Boot sequence started (<_start>) at %t", $time);
                    boot_sequence_once = 1;
                end
                
            end

            SYM_BSS_LOOP:  begin
                if (!bss_loop_once) begin
                    current_context = "BSS Loop";
                    $fdisplay(log_file, "\n[FW_MON] 🧹 Initializing .bss section (<bss_loop>) at %t", $time); 
                    bss_loop_once = 1;
                end
            end
                        
            SYM_DATA_LOOP: begin
                if (!data_loop_once) begin
                    current_context = "DATA Loop";
                    $fdisplay(log_file, "\n[FW_MON] 💾 Copying .data section (<data_loop>) at %t", $time);
                    data_loop_once = 1;
                end
            end
            
            SYM_MAIN: begin
                current_context = "Main Entry";
                $fdisplay(log_file, "\n[FW_MON] ✅ Jump to main() application at %t", $time);
                check_data_integrity(); 
            end

            SYM_SYSTEM_INIT: begin
                current_context = "SYSTEM INIT";
                $fdisplay(log_file, "\n[FW_MON] ✅ Jump to system_init() function at %t", $time);
            end
            
            SYM_PERIPHERALS_INIT: begin
                current_context = "Periph INIT Process";
                $fdisplay(log_file, "\n[FW_MON] ✅ Jump to peripherals_init() - Initialize UART/TIMER/GPIO function at %t", $time);
            end

            SYM_PERIPHERAL_IS_INITIALIZED: begin
                current_context = "Periph INIT CHECK";
                $fdisplay(log_file, "\n[FW_MON] ✅ Jump to peripheral_is_initialized() - Check if UART/TIMER/GPIO function at %t", $time);
            end

            SYM_UART_INIT: begin
                current_context = "Periph UART INIT";
                $fdisplay(log_file, "\n[FW_MON] ✅ Jump to peripherals_init() - uart_init() function at %t", $time);
            end

            SYM_UART_CONFIGURE: begin
                current_context = "Periph UART CONFIG";
                $fdisplay(log_file, "\n[FW_MON] ✅ Jump to peripherals_init() - uart_configure() function at %t", $time);
            end

            SYM_UART_DEINIT: begin
                current_context = "Periph UART DEINIT";
                $fdisplay(log_file, "\n[FW_MON] ✅ Jump to peripherals_init() - uart_deinit() function at %t", $time);
            end

            SYM_GPIO_INIT: begin
                current_context = "Periph GPIO INIT";
                $fdisplay(log_file, "\n[FW_MON] ✅ Jump to peripherals_init() - gpio_init() function at %t", $time);
            end

            SYM_GPIO_CONFIGURE_PIN: begin
                current_context = "Periph GPIO CONFIG PIN";
                $fdisplay(log_file, "\n[FW_MON] ✅ Jump to peripherals_init() - gpio_configure_pin() function at %t", $time);
            end

            SYM_GPIO_DEINIT: begin
                current_context = "Periph GPIO DEINIT";
                $fdisplay(log_file, "\n[FW_MON] ✅ Jump to peripherals_init() - gpio_deinit() function at %t", $time);
            end

            SYM_TIMER_INIT: begin
                current_context = "Periph TIMER INIT";
                $fdisplay(log_file, "\n[FW_MON] ✅ Jump to peripherals_init() - timer_init() function at %t", $time);
            end

            SYM_TIMER_DEINIT: begin
                current_context = "Periph TIMER DEINIT";
                $fdisplay(log_file, "\n[FW_MON] ✅ Jump to peripherals_init() - timer_deinit() function at %t", $time);
            end

            SYM_SYSTEM_INIT_WITH_TIMER_SAFE: begin
                current_context = "System Timer Init with Safety function";
                $fdisplay(log_file, "\n[FW_MON] ✅ Jump to peripherals_init() - system_init_with_timer_safe() function at %t", $time);
            end

            // SYM_APP_PRINT_STRING: begin
            //     current_context = "System Print with Safety function";
            //     $fdisplay(log_file, "\n[FW_MON] ✅ Jump to app_print_string() function - Display_system_info_safe/ at %t", $time);
            // end

            SYM_HANDLE_CRITICAL_ERROR: begin
                current_context = "Main Handle Critical Error function";
                $fdisplay(log_file, "\n[FW_MON] ✅ Jump to handle_critical_error() function - main/ at %t", $time);
            end

            SYM_DISPLAY_SYSTEM_INFO_ISRA_0: begin
                current_context = "Main Display System Info function";
                $fdisplay(log_file, "\n[FW_MON] ✅ Jump to display_system_info() function - main/ at %t", $time);
            end

            SYM_BLINK_LED_DEMO: begin
                current_context = "Main Blink Led Demo function";
                $fdisplay(log_file, "\n[FW_MON] ✅ Jump to blink_led_demo() function - main/ at %t", $time);
            end

            // SYM_GPIO_WRITE_PIN: begin
            //     current_context = "Main Blink Led Demo - GPIO_WRITE_PIN function";
            //     $fdisplay(log_file, "\n[FW_MON] ✅ Jump to gpio_write_pin() function - blink_led_demo/ at %t", $time);
            // end


            // SYM_SYSTEM_DELAY_MS_SAFE: begin
            //     current_context = "Main Blink Led Demo - SYSTEM_DELAY_MS_SAFE function";
            //     $fdisplay(log_file, "\n[FW_MON] ✅ Jump to system_delay_ms_safe() function - blink_led_demo/ at %t", $time);
            // end

        endcase
    end


    task check_data_integrity;
        integer i;
        reg [31:0] addr;
        reg [31:0] ram_val;
        reg [31:0] expected_val;
        begin
            $fdisplay(log_file, "\n[TB][VERIFY] Checking .data integrity...");
            
            // The generated symbols are used to determine the exact range
            // SYM__SDATA = début RAM (0x10000000)
            // SYM__EDATA = fin RAM (0x10000004 ou plus)
            // SYM_VERIFICATION_CANARY = Variable address (0x10000000)
            
            if (SYM__EDATA <= SYM__SDATA) begin
                $fdisplay(log_file, "[TB][WARNING] .data section is empty (Size 0). Nothing to verify.");
            end else begin
                // Specific verification of our CANARY
                // The information is read directly from the Verilog model's memory table (Backdoor access).
                
                // index = (Adresse - Base) / 4
                ram_val = dut.top_soc_inst.dmem_inst.dmem_inst.mem[(SYM_VERIFICATION_CANARY - 32'h10000000)/4];
                
                // Expected Value: 0xCAFEBABE
                if (ram_val === 32'hCAFEBABE) begin
                    $fdisplay(log_file, "[TB][PASS] ✅ Verification Canary found: %h at address %h", ram_val, SYM_VERIFICATION_CANARY);
                end else begin
                    $fdisplay(log_file, "[TB][FAIL] ❌ Data Mismatch! Addr: %h, Read: %h, Expected: CAFEBABE", SYM_VERIFICATION_CANARY, ram_val);
                    $stop; // Critical Error: Stop Simulation
                end
            end
            $fdisplay(log_file, "------------------------------------------------------------\n");
        end
    endtask

    
    // =======================================================================
    // UART RX MONITOR 
    // =======================================================================
    initial begin
        // Wait for reset release 
        wait(rst_n == 1);
        $fdisplay(log_file, "\n[UART TERMINAL] Listening...");

        forever begin
            // 1. Wait for Start bit (Falling Edge)
            @(negedge uart_tx);

            // 2. Wait hakf bit period to sample middle of start bit
            repeat (BAUD_PERIOD / 2) @(posedge clk);

            if (uart_tx == 0) begin
                uart_captured_byte = 0;

                // 3. Sample 8 data bits
                for (i_gen = 0; i_gen < 8; i_gen++) begin
                    repeat (BAUD_PERIOD) @(posedge clk);
                    uart_captured_byte[i_gen] = uart_tx;
                end

                // 4. Wait for stop bit
                repeat (BAUD_PERIOD) @(posedge clk);

                // 5. Store and Process
                uart_tx_buffer[uart_tx_total] = uart_captured_byte;
                uart_tx_total = uart_tx_total + 1;

                // Print for python script: parse_uart
                if (log_file != 0) $fwrite(log_file, "\n[UART TERMINAL] %c", uart_captured_byte);
                
                // Use for direct terminal display
                //process_uart_byte(uart_captured_byte);
            end
        end
    end


    // =======================================================================
    // UART PROCESSING TASKS
    // =======================================================================
    reg [7:0] print_buffer [0:255];
    integer   print_idx = 0;
    integer   k_gen;

    task process_uart_byte;
        input [7:0] byte_data;
        begin
            // If it's a line break (\n or \r)
            if (byte_data == 8'h0A || byte_data == 8'h0D) begin
                if (print_idx > 0) begin
                    // Print Prefix
                    if (log_file != 0) $fwrite(log_file, "[UART TERMINAL] ");
                    
                    // We force a line break at the very end
                    for (k_gen = 0; k_gen < print_idx; k_gen = k_gen + 1) begin
                        if (log_file != 0) $fwrite(log_file, "%c", print_buffer[k_gen]);
                    end
                    
                    // 
                    if (log_file != 0) $fwrite(log_file, "\n");
                    
                    print_idx = 0; // We empty the box for the next line
                end
            end 
            // We only store readable ASCII characters (avoids corrupted characters)
            else if (byte_data >= 8'h20 && byte_data <= 8'h7E) begin
                print_buffer[print_idx] = byte_data;
                print_idx = print_idx + 1;
            end
        end
    endtask



    // ======================================================================
    // GPIO MONITORING & VISUAL LED SIMULATION
    // ======================================================================
    always @(gpio_monitor) begin
        if (cycle_count > 100) begin
            // Only monitor bit 0 (our LED)
            if (gpio_monitor[0] != gpio0_state) begin

                // Visualization
                if (gpio_monitor[0] == 1'b1) begin
                    if (log_file != 0) $fdisplay(log_file, "\n[GPIO] LED 0: 🟢 ON   (Temps: %0t ns)", $time);
                end else begin
                    if (log_file != 0) $fdisplay(log_file, "\n[GPIO] LED 0: ⚪ OFF  (Temps: %0t ns)", $time);
                end

                gpio0_transitions = gpio0_transitions + 1;
                
                // Period check
                if (last_gpio0_change > 0) begin
                    // integer period = cycle_count - last_gpio0_change;
                    // Add specific checks here if needed
                end
                
                gpio0_state = gpio_monitor[0];
                last_gpio0_change = cycle_count;
            end
        end
    end

    // ======================================================================
    // HELPERS
    // ======================================================================
    task verify_overall_behavior;
        begin
            $fdisplay(log_file, "--------------------------------");
            
            // 1. Check UART Activity
            if (uart_tx_total > 10) begin
                $fdisplay(log_file, "[PASS] UART Activity Detected (%0d bytes)", uart_tx_total);
            end else begin
                $fdisplay(log_file, "[FAIL] No UART Activity");
                tests_failed = tests_failed + 1;
            end
            
            // 2. Check GPIO Activity
            if (gpio0_transitions > 0) begin
                $fdisplay(log_file, "[PASS] GPIO Activity Detected (%0d toggles)", gpio0_transitions);
            end else begin
                $fdisplay(log_file, "[FAIL] No GPIO Activity detected (Increase timeout if needed)");
                tests_failed = tests_failed + 1;
            end
            
            $fdisplay(log_file, "Total Passed: %0d, Total Failed: %0d", (tests_failed == 0 ? 2 : 0), tests_failed);
        end
    endtask


    // =======================================================================
    // CPU Trace Logger
    // =======================================================================
    always @(posedge clk) begin
        if (cpu_trace_log && dut.top_soc_inst.cpu_rst_n) begin
            $fdisplay(cpu_trace_log,
                "%8d        | %08h  %08h | %08h  %08h | %08h  %08h | %08h  %08h | %08h  %08h",
                cycle_count,
                fetch_pc    , fetch_instr     ,
                decode_pc   , decode_instr    ,
                execute_pc  , execute_instr   ,
                mem_pc      , mem_instr       ,
                writeback_pc, writeback_instr ,
            );
            $fdisplay(cpu_trace_log,
                "-------------------------------------------------------------------------------------------------------------------------------------");
        end
    end


    // =======================================================================
    // WAVEFORM DUMP
    // =======================================================================
    initial begin
        $dumpfile("minisoc_c_firmware.vcd");
        $dumpvars(0, tb_minisoc_c_firmware);
        $fdisplay(log_file, "[TB] Waveform dumping enabled: minisoc_c_firmware.vcd");
    end

endmodule