# =============================================================================
# vivado_project.tcl — Create Vivado project for MiniSoC_RV32I on Arty Z7-20
# =============================================================================
#
# Usage (from the fpga/ directory, or via Makefile):
#   vivado -mode batch -source fpga/vivado_project.tcl
#
# The script resolves all source paths relative to the repository root.
# It assumes the Vivado project lives in:
#   <repo_root>/build/fpga/minisoc_arty_z7/
#
# Variables you may override on the command line:
#   -tclargs REPO_ROOT=<absolute path>
# =============================================================================

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------

# Default: TCL file sits in <repo_root>/fpga/, so root is one level up
set script_dir  [file dirname [file normalize [info script]]]
set repo_root   [file normalize "$script_dir/.."]

# Allow override: vivado -mode batch -source ... -tclargs REPO_ROOT=/path
foreach arg $argv {
    if {[regexp {^REPO_ROOT=(.+)$} $arg -> val]} {
        set repo_root [file normalize $val]
    }
}

set project_dir "$repo_root/build/fpga"
set project_name "minisoc_arty_z7"

puts "INFO: Repository root : $repo_root"
puts "INFO: Project directory: $project_dir/$project_name"

# ---------------------------------------------------------------------------
# Create project
# ---------------------------------------------------------------------------
file mkdir $project_dir

create_project $project_name "$project_dir/$project_name" -part xc7z020clg400-1 -force

set_property board_part digilentinc.com:arty-z7-20:part0:1.1 [current_project]

# ---------------------------------------------------------------------------
# Add RTL sources — Hardware
# ---------------------------------------------------------------------------

# FPGA top wrapper (this repo, fpga/ directory)
add_files -norecurse [list \
    "$repo_root/fpga/top_arty_z7.v" \
]

# SoC top
add_files -norecurse [list \
    "$repo_root/src/top/top_soc.v" \
    "$repo_root/src/top/mini_rv32i_top.v" \
]

# CPU
add_files [glob "$repo_root/src/cpu/*.v"]

# Bus
add_files [glob "$repo_root/src/bus/*.v"]

# Memories
add_files [glob "$repo_root/src/mem/imem/*.v"]
add_files [glob "$repo_root/src/mem/dmem/*.v"]
add_files [glob "$repo_root/src/mem/mem_init/*.v"]

# Peripherals
add_files [glob "$repo_root/src/peripheral/uart/*.v"]
add_files [glob "$repo_root/src/peripheral/timer/*.v"]
add_files [glob "$repo_root/src/peripheral/gpio/*.v"]

# Pad (io_pad generic — used by top_soc; FPGA IO are handled by synthesis)
add_files [glob "$repo_root/src/pad/*.v"]

# Common headers (include dirs)
set_property include_dirs [list \
    "$repo_root/src/common" \
] [current_fileset]

# ---------------------------------------------------------------------------
# Add firmware memory initialisation file
# ---------------------------------------------------------------------------
# firmware.mem is generated by 'make fpga-firmware' into build/fpga/
# We declare it as a data file so Vivado copies it into the impl directory.
set fw_mem "$project_dir/firmware.mem"
if {[file exists $fw_mem]} {
    add_files -fileset [get_filesets sim_1] $fw_mem
    puts "INFO: firmware.mem found and added."
} else {
    puts "WARNING: $fw_mem not found. Run 'make fpga-firmware' first, then re-run this script."
}

# ---------------------------------------------------------------------------
# Add constraints
# ---------------------------------------------------------------------------
add_files -fileset [get_filesets constrs_1] -norecurse \
    "$repo_root/fpga/arty_z7_20.xdc"

# ---------------------------------------------------------------------------
# Set top module
# ---------------------------------------------------------------------------
set_property top top_arty_z7 [current_fileset]
update_compile_order -fileset sources_1

# ---------------------------------------------------------------------------
# Synthesis settings
# ---------------------------------------------------------------------------
set_property strategy "Vivado Synthesis Defaults" [get_runs synth_1]

# ---------------------------------------------------------------------------
# Implementation settings
# ---------------------------------------------------------------------------
set_property strategy "Performance_ExplorePostRoutePhysOpt" [get_runs impl_1]

# ---------------------------------------------------------------------------
# Optional: run synthesis + implementation + bitstream in batch mode
# Comment out if you just want the project created (to open in GUI).
# ---------------------------------------------------------------------------
# launch_runs synth_1 -jobs 4
# wait_on_run synth_1
# launch_runs impl_1 -to_step write_bitstream -jobs 4
# wait_on_run impl_1

puts ""
puts "============================================================"
puts " Project created: $project_dir/$project_name"
puts " Open in Vivado GUI:"
puts "   vivado $project_dir/$project_name/$project_name.xpr"
puts ""
puts " Or build bitstream in batch:"
puts "   make fpga-bitstream"
puts "============================================================"